### ISSUE TITLE
[waitlist] update sequences diagram

### ISSUE THREAD

**Issue by whyvrafvr** [fairhive-labs/docs#29]

**Comment by s4m5ep10l** [comment]
@whyvrafvr I can get this one. 
I will update the sequences diagram. 
Provide source plz.

**Comment by whyvrafvr** [comment]
Cool. I'll send you the source on telegram. It's a flat file (.txt). 

Assigning you.

**Comment by whyvrafvr** [comment]
[Pre-registration_Workflow_v1.2.txt](https://github.com/fairhive-labs/docs/files/12905831/Pre-registration_Workflow_v1.2.txt)

**Comment by whyvrafvr** [comment]
@s4m5ep10l you can use https://sequencediagram.org/ it's a free tool. 

I've already used it 🆗

**Comment by s4m5ep10l** [comment]
I use https://www.websequencediagrams.com/

Your tool looks better. Very simple. 

I've to move
See ya

**Comment by s4m5ep10l** [comment]
> Cool. I'll send you the source on telegram. It's a flat file (.txt).
> 
> Assigning you.

BTW, better chat on DREAD ;)

**Comment by whyvrafvr** [comment]
Gotcha. No problem there anyway.

**Comment by s4m5ep10l** [comment]
What color do we use for the background ? I mean `participantgroup`

**Comment by whyvrafvr** [comment]
you can use #80DEEA

**Comment by whyvrafvr** [comment]
sorry, was replying in issue 31 LMFAO

**Comment by whyvrafvr** [comment]
you can also use #9575CD

**Comment by s4m5ep10l** [comment]
done ✅ 

[Pre-registration_Workflow_v2.0.txt](https://github.com/fairhive-labs/docs/files/12907020/Pre-registration_Workflow_v2.0.txt)

**Comment by whyvrafvr** [comment]
nice! I will export and swap existing one in Gitbook. Thx :pray:

**Comment by s4m5ep10l** [comment]
You're welcome

**Comment by s4m5ep10l** [comment]
I'll do it, don't worry. And I will update the assets in Gitbook.

**Comment by whyvrafvr** [comment]
OK, GO

**Comment by s4m5ep10l** [comment]
dawn; I cannot push :(

**Comment by whyvrafvr** [comment]
yes, you now have a write access

**Comment by s4m5ep10l** [comment]
ok
